//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace check_cafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Change()
        {
            this.Table = new HashSet<Table>();
        }

        public System.Guid Id { get; set; }
        public string Adres { get; set; }
        public System.DateTime Date_in { get; set; }
        public Nullable<System.DateTime> Date_out { get; set; }
        public System.Guid Host { get; set; }
        public Nullable<System.Guid> Administrator { get; set; }
        public Nullable<System.Guid> Barista { get; set; }
        public Nullable<System.Guid> Povar { get; set; }
        public Nullable<System.Guid> Oficiant1 { get; set; }
        public Nullable<System.Guid> Oficiant2 { get; set; }
        public Nullable<System.Guid> Hostes { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual Employee Employee4 { get; set; }
        public virtual Employee Employee5 { get; set; }
        public virtual Employee Employee6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table> Table { get; set; }
    }
}
