//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace check_cafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public System.Guid Id { get; set; }
        public System.Guid Client { get; set; }
        public int Number_table { get; set; }
        public System.DateTime Date_in { get; set; }
        public Nullable<System.DateTime> Date_out { get; set; }
        public int Number_seat { get; set; }
        public System.Guid Id_Change { get; set; }

        public virtual Change Change { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
